from datetime import datetime
from math import isfinite
from statistics import median
from zoneinfo import ZoneInfo

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from modules.premium_engine import CATALOG, demo_chain, generate, payoff
from modules.ui import configure_page


def money(value):
    return f"${value:,.2f}" if isfinite(value) else "Unlimited"


def render():
    configure_page("AlphaOS | Premium Studio")
    st.markdown("""<style>
    .stApp {background: #0b111c;}
    [data-testid="stSidebar"] {background: #101a29;}
    .block-container {max-width: 1480px; padding-top: 2.2rem;}
    h1 {letter-spacing: -1.8px; font-weight: 750 !important;}
    [data-testid="stMetric"] {background: #121e2e; border: 1px solid #23344b; padding: 18px; border-radius: 12px;}
    .eyebrow {color: #61d8c1; letter-spacing: 3px; font-size: 12px; font-weight: 700;}
    </style>""", unsafe_allow_html=True)
    with st.sidebar:
        st.markdown("## ◈ AlphaOS")
        st.caption("PREMIUM STUDIO")
        st.divider()
        source = st.radio("Market data", ["Demo · synthetic", "Public · connected quotes"])
        st.caption("Research workspace • No order execution")
        st.divider()
        st.write("01  Set your horizon\n\n02  Compare income trades\n\n03  Inspect the payoff")
        st.page_link("pages/9_Settings.py", label="Connections & settings")
    st.markdown('<div class="eyebrow">OPTIONS / INCOME RESEARCH</div>', unsafe_allow_html=True)
    st.title("Make time your edge.")
    st.write("Explore premium-selling trades by expiration, risk, and estimated probability of profit.")
    demo = source.startswith("Demo")
    if demo:
        st.info("DEMO DATA — Illustrative $500 underlying and synthetic quotes. These are not current market trades.")
    finder, library, methodology = st.tabs(["Trade finder", "Strategy library", "How the numbers work"])
    with library:
        st.subheader("The premium-selling toolkit")
        st.dataframe(pd.DataFrame([{"Strategy": name, "Outlook": v[0], "Risk family": v[1], "Construction": v[2]} for name, v in CATALOG.items()]), hide_index=True, use_container_width=True)
        st.markdown("**Multi-expiration and lifecycle strategies**")
        st.write("Calendars, diagonals, poor man's covered calls, and double diagonals need cross-expiration pricing and a volatility model for the remaining long option. They are not generated by this engine. The wheel is a sequence of cash-secured puts and covered calls; both stages are available individually. Collars and debit strategies are outside this premium-credit scanner. This library covers major income structures, not every possible option combination.")
        st.link_button("Explore the OIC strategy reference", "https://www.optionseducation.org/strategies/all-strategies-en")
    with methodology:
        st.markdown("""**Estimated probability of profit (POP)** integrates a lognormal terminal-price distribution over all price intervals with positive expiration P&L after entry commissions. The model assumes zero price drift and constant annualized volatility. This is not a historical win rate, a guarantee, or the probability of hitting an early profit target.

**Volatility:** a manual annualized assumption or median IV of the eight contracts closest to spot. Provider IV must be a decimal (0.25 = 25%). Missing IV leaves POP unavailable. Same-day POP is withheld because precise settlement times and an intraday model are needed.

**Risk : reward** = maximum expiration loss ÷ maximum expiration profit. 3 : 1 means risking $3 to earn at most $1. Unlimited risk is displayed explicitly. Return on risk is maximum profit divided by maximum loss, not expected return.

**Pricing:** Natural sells at bid and buys at ask; Midpoint assumes fills halfway between bid and ask. Missing, crossed, negative, and nonfinite quotes are excluded. Entry fees are per option contract. Exit fees, slippage, stock commissions, and taxes are excluded.

**Position basis:** one strategy unit, standard 100-share contracts. Covered positions include shares purchased at the displayed spot. Cash-secured puts reserve strike × 100; covered strangles also reserve assignment cash. No broker margin estimate is made. Early assignment, exercise, dividends, and settlement differences can change realized results; verify contract specifications.""")
    with finder:
        with st.form("premium_scan"):
            a, b, c = st.columns([1, 1, 2])
            symbol = a.selectbox("Underlying", ["SPY", "QQQ", "IWM", "DIA", "SPX", "XSP"])
            horizon = b.selectbox("Timeframe", ["Same day", "1–7 days", "8–21 days", "30–45 days", "60–90 days", "Custom"], index=3)
            bounds = c.slider("Custom expiration range · days", 0, 180, (30, 45))
            a, b, c = st.columns(3)
            outlook = a.selectbox("Market outlook", ["Any", "Bullish", "Neutral", "Bearish"])
            families = b.multiselect("Risk families", ["Defined", "Stock-backed", "Uncovered"], default=["Defined"])
            budget = c.number_input("Maximum loss per unit ($)", min_value=0.0, value=1500.0, step=100.0, help="Zero disables the budget filter, including for unlimited risk.")
            strategies = st.multiselect("Strategies", list(CATALOG), default=list(CATALOG))
            with st.expander("Pricing & model assumptions"):
                a, b, c = st.columns(3)
                width = a.number_input("Target wing width ($)", min_value=1.0, value=5.0)
                pricing = b.selectbox("Fill assumption", ["Natural", "Midpoint"])
                fee = c.number_input("Entry fee / option contract ($)", min_value=0.0, value=0.65, step=0.05)
                a, b, c = st.columns(3)
                iv_mode = a.selectbox("Volatility source", ["Manual assumption", "Chain ATM IV"])
                manual_iv = b.number_input("Annualized volatility (%)", min_value=1.0, max_value=500.0, value=25.0)
                min_pop = c.slider("Minimum estimated POP (%)", 0, 99, 0)
            submitted = st.form_submit_button("Find premium trades →", type="primary", use_container_width=True)
        if submitted:
            st.session_state["premium_scan_version"] = st.session_state.get("premium_scan_version", 0) + 1
            ranges = {"Same day": (0, 0), "1–7 days": (1, 7), "8–21 days": (8, 21), "30–45 days": (30, 45), "60–90 days": (60, 90), "Custom": bounds}
            low, high = ranges[horizon]
            now = datetime.now(ZoneInfo("America/New_York"))
            today = now.date()
            rows, errors = [], []
            with st.spinner("Building expiration payoffs and probability estimates…"):
                try:
                    quote_time = "Synthetic"
                    if demo:
                        spot = 500.0
                        chains = [demo_chain(d, as_of=today) for d in sorted(set([low, (low + high) // 2, high]))]
                    else:
                        from modules.public_data import get_public_option_chain, get_public_option_expirations, get_public_quotes
                        quotes = get_public_quotes((symbol,))
                        q = next((q for q in quotes if q["symbol"] == symbol), None)
                        if not q or not q.get("last") or not isfinite(q["last"]) or q["last"] <= 0:
                            raise ValueError("Underlying quote unavailable.")
                        spot = q["last"]
                        quote_time = str(q.get("updated_at") or "Unavailable")
                        expirations = [e for e in get_public_option_expirations(symbol) if low <= (datetime.fromisoformat(e).date() - today).days <= high]
                        chains = []
                        for expiration in expirations:
                            try:
                                chains.append(get_public_option_chain(symbol, expiration))
                            except Exception:
                                errors.append(f"Chain unavailable: {expiration}")
                    for chain in chains:
                        dte = (datetime.fromisoformat(chain["expiration"]).date() - today).days
                        iv = manual_iv / 100
                        if iv_mode == "Chain ATM IV":
                            contracts = sorted(chain["calls"] + chain["puts"], key=lambda c: abs((c.get("strike") or 0) - spot))[:8]
                            values = [c["iv"] for c in contracts if c.get("iv") is not None and isfinite(c["iv"]) and 0 < c["iv"] <= 5]
                            iv = median(values) if values else None
                        for row in generate(chain, spot, max(dte, 0.25) / 365, iv, width, fee, pricing, today):
                            if dte == 0:
                                row["pop"] = None
                            row.update(dte=dte, iv=iv)
                            bias, family, _ = CATALOG[row["strategy"]]
                            if row["strategy"] not in strategies or family not in families or (outlook != "Any" and bias != outlook):
                                continue
                            if not demo and symbol in ("SPX", "XSP") and (row["shares"] or row["strategy"] == "Cash-secured put"):
                                continue  # An index cannot be purchased as 100 shares.
                            if budget and row["max_loss"] > budget:
                                continue
                            if min_pop and (row["pop"] is None or row["pop"] * 100 < min_pop):
                                continue
                            rows.append(row)
                    rows.sort(key=lambda r: (-(r["pop"] if r["pop"] is not None else -1), r["risk_reward"]))
                    st.session_state["premium_result"] = dict(rows=rows, source=source, symbol="DEMO" if demo else symbol,
                        spot=spot, fetched=now.strftime("%Y-%m-%d %H:%M %Z"), quote_time=quote_time,
                        scope=f"{low}–{high} DTE · {pricing} fills · {iv_mode}", errors=errors)
                except Exception:
                    st.session_state.pop("premium_result", None)
                    st.error("Could not load market data. Check the Public connection in Settings and try again. No demo data was substituted.")
        result = st.session_state.get("premium_result")
        if not result or result["source"] != source:
            st.caption("Choose your horizon and run a scan to compare potential trades.")
            return
        rows = result["rows"]
        st.caption(f"{result['symbol']} · {result['scope']} · Retrieved {result['fetched']} · Underlying timestamp: {result['quote_time']}")
        st.caption("Last submitted scan. Submit again to apply changed filters. Provider bid/ask timestamps appear in the contract details when available; retrieval time is not exchange time.")
        for error in result["errors"]:
            st.warning(error)
        if not rows:
            st.info("No eligible trades match. Try more strategies, another risk budget, or a wider expiration range.")
            return
        a, b, c, d = st.columns(4)
        a.metric("Matching trades", len(rows))
        b.metric("Underlying", money(result["spot"]))
        pops = [r["pop"] for r in rows if r["pop"] is not None]
        c.metric("Highest model POP", f"{max(pops):.1%}" if pops else "Unavailable")
        d.metric("Strategies represented", len({r["strategy"] for r in rows}))
        st.subheader("Your opportunity set")
        st.caption("Sorted by estimated POP, then lower risk/reward. High POP does not imply positive expected returns.")
        table = pd.DataFrame([{
            "#": i + 1, "Strategy": r["strategy"], "Expiration": r["expiration"], "DTE": r["dte"],
            "Strikes": " / ".join(f"{'Buy' if l['qty'] > 0 else 'Sell'} {abs(l['qty'])} {l['strike']:g}{l['type'][0]}" for l in r["legs"]),
            "Credit / unit": money(r["credit"] * 100), "Max profit": money(r["max_profit"]),
            "Max loss": money(r["max_loss"]), "Risk : reward": f"{r['risk_reward']:.2f} : 1" if isfinite(r["risk_reward"]) else "Unlimited",
            "Est. POP": f"{r['pop']:.1%}" if r["pop"] is not None else "Unavailable",
        } for i, r in enumerate(rows)])
        st.caption("Click a row to inspect its strikes, contracts, and payoff below.")
        event = st.dataframe(table, hide_index=True, use_container_width=True,
            on_select="rerun", selection_mode="single-row",
            key=f"opportunities_{st.session_state.get('premium_scan_version', 0)}")
        st.download_button("Export scan · CSV", table.to_csv(index=False), "alphaos-premium-scan.csv", "text/csv")
        if not event.selection.rows:
            st.info("Select an opportunity row to view the trade details.")
            return
        selected = event.selection.rows[0]
        r = rows[selected]
        st.session_state["quant_selected_option"] = {**r, "symbol": result["symbol"], "source": result["source"]}
        st.markdown(f"### Trade {selected + 1} · {result['symbol']} · {r['expiration']}")
        left, right = st.columns([2, 1])
        with left:
            strikes = [x["strike"] for x in r["legs"]]
            lower, upper = max(0, min(min(strikes) * 0.9, r["spot"] * 0.85)), max(max(strikes) * 1.1, r["spot"] * 1.15)
            x = sorted(set([lower + (upper-lower)*i/300 for i in range(301)] + strikes + [b for b in r["breakevens"] if lower <= b <= upper]))
            y = [payoff(r["legs"], r["credit"], p, r["shares"], r["spot"], r["fees"]) for p in x]
            fig = go.Figure(go.Scatter(x=x, y=y, mode="lines", line=dict(color="#61d8c1", width=3), fill="tozeroy", fillcolor="rgba(97,216,193,0.08)", name="Expiration P&L"))
            fig.add_hline(y=0, line_color="#65758b")
            fig.add_vline(x=r["spot"], line_dash="dot", annotation_text="Spot")
            fig.update_layout(template="plotly_dark", paper_bgcolor="#0b111c", plot_bgcolor="#0b111c", height=360, margin=dict(l=15, r=15, t=30, b=20), xaxis_title="Underlying at expiration ($)", yaxis_title="P&L per unit ($)")
            st.plotly_chart(fig, use_container_width=True)
        with right:
            st.markdown(f"### {r['strategy']}")
            st.write(CATALOG[r["strategy"]][2])
            st.write("**Breakevens:** " + (", ".join(money(x) for x in r["breakevens"]) or "None"))
            st.write(f"**Model volatility:** {r['iv']:.1%}" if r["iv"] else "**Model volatility:** unavailable")
            st.write(f"**Entry commissions:** {money(r['fees'])}")
            st.write(f"**Return on max risk:** {r['max_profit']/r['max_loss']:.1%}" if isfinite(r["max_loss"]) else "**Return on max risk:** undefined")
            if r["strategy"] in ("Cash-secured put", "Covered strangle"):
                reserve = sum(x["strike"] * 100 * -x["qty"] for x in r["legs"] if x["type"] == "Put" and x["qty"] < 0)
                st.write(f"**Put assignment cash:** {money(reserve)}")
            if r["shares"]:
                st.write(f"**Stock purchase:** {r['shares']} shares / {money(r['shares'] * r['spot'])}")
            if not isfinite(r["max_loss"]):
                st.warning("Unlimited loss potential. The chart shows only a finite price range.")
        st.dataframe(pd.DataFrame([{"Action": "Buy" if l["qty"] > 0 else "Sell", "Contracts": abs(l["qty"]), "Type": l["type"], "Strike": l["strike"], "Bid": l["bid"], "Ask": l["ask"], "Contract": l.get("contract", "Unavailable")} for l in r["legs"]]), hide_index=True, use_container_width=True)
        if result['source'].startswith('Public'):
            st.dataframe(pd.DataFrame([{'Contract': l.get('contract'), 'Bid timestamp':str(l.get('bid_timestamp') or 'Unavailable'),
                'Ask timestamp':str(l.get('ask_timestamp') or 'Unavailable'), **{g:l.get(g) for g in ('delta','gamma','theta','vega','rho','iv')}} for l in r['legs']]),hide_index=True,use_container_width=True)
        st.caption("Estimates assume standard contracts held to expiration. Review settlement, assignment exposure, and quote freshness before acting.")
